### ISSUE TITLE
Sharing iP code quality feedback [for @jiakai-17]

### ISSUE THREAD

**Issue by soc-se-script** [jiakai-17/ip#12]
@jiakai-17 We did an automated analysis of your code to detect potential areas to improve the code quality. We are sharing the results below, to help you improve the iP code further.

IMPORTANT: Note that the script looked for **just a few easy-to-detect problems only**, and **at-most three example are given** i.e., there can be other areas/places to improve.

### Aspect: Tab Usage

No easy-to-detect issues :+1: 

### Aspect: Naming boolean variables/methods

No easy-to-detect issues :+1: 

### Aspect: Brace Style

No easy-to-detect issues :+1: 

### Aspect: Package Name Style

No easy-to-detect issues :+1: 

### Aspect: Class Name Style

No easy-to-detect issues :+1: 

### Aspect: Dead Code

No easy-to-detect issues :+1: 

### Aspect: Method Length

Example from [`src/main/java/duke/tasks/TaskList.java` lines `282-337`](https://github.com/jiakai-17/ip/blob/cec39d804c6bf93ae7827ec374a8631a48eefb7f/src/main/java/duke/tasks/TaskList.java#L282..L337):

```java

    public String edit(int num, String editCommand) {
        int index = num - 1;
        if (index < 0 || index >= tasks.size()) {
            throw new DukeIllegalArgumentException(ERROR_MESSAGE_INDEX_OUT_OF_BOUNDS);
        }
        Task editingTask = tasks.get(index);

        String newDescription = null;
        String newBy = null;
        String newStartDateTime = null;
        String newEndDateTime = null;

        // Split the edit command into flags and values
        List<List<String>> flagsAndValues = Arrays.stream(editCommand.split(" ((?=/[dbse] ))"))
                .map(String::trim)
                .filter(s -> s.matches("/[dbse] .*"))
                .map(s -> List.of(s.substring(0, 2), s.substring(3)))
                .collect(toList());

        for (List<String> flagAndValue : flagsAndValues) {
            String flag = flagAndValue.get(0);
            String value = flagAndValue.get(1);

            // Check which flag was found
            if ("/d".equals(flag)) {
                newDescription = value;
            } else if ("/b".equals(flag)) {
                newBy = value;
            } else if ("/s".equals(flag)) {
                newStartDateTime = value;
            } else if ("/e".equals(flag)) {
                newEndDateTime = value;
            }
        }

        // Check if any parameters were supplied
        if (newDescription == null && newBy == null && newStartDateTime == null && newEndDateTime == null) {
            return MESSAGE_TASK_NOT_UPDATED;
        }

        // Respond accordingly based on task type
        if (editingTask instanceof ToDo) {
            return updateTodoTask((ToDo) editingTask, newDescription);
        }

        if (editingTask instanceof Deadline) {
            return updateDeadlineTask((Deadline) editingTask, newDescription, newBy);
        }

        if (editingTask instanceof Event) {
            return updateEventTask((Event) editingTask, newDescription, newStartDateTime, newEndDateTime);
        }

        // Should not reach here.
        throw new DukeIllegalArgumentException("Task type not recognised.");
    }

```

Example from [`src/test/java/duke/tasks/TaskListTest.java` lines `62-113`](https://github.com/jiakai-17/ip/blob/cec39d804c6bf93ae7827ec374a8631a48eefb7f/src/test/java/duke/tasks/TaskListTest.java#L62..L113):

```java

    public void add_wrongTaskType_exceptionThrown() {
        String fileName = "test_add.txt";
        Storage storage = new Storage(fileName);
        storage.save("");

        TaskList taskList = new TaskList(fileName);
        // Trying to add as TODO
        try {
            taskList.add(TaskList.TaskType.DEADLINE, "deadline");
            fail();
        } catch (Exception e) {
            assertEquals("Only ToDo tasks can be added with just a description.", e.getMessage());
        }
        try {
            taskList.add(TaskList.TaskType.EVENT, "event");
            fail();
        } catch (Exception e) {
            assertEquals("Only ToDo tasks can be added with just a description.", e.getMessage());
        }

        // Trying to add as Deadline
        try {
            taskList.add(TaskList.TaskType.TODO, "todo", "2023-08-26 23:59");
            fail();
        } catch (Exception e) {
            assertEquals("Only Deadline tasks can be added with a description and deadline.",
                    e.getMessage());
        }
        try {
            taskList.add(TaskList.TaskType.EVENT, "event", "2023-08-26 23:59");
            fail();
        } catch (Exception e) {
            assertEquals("Only Deadline tasks can be added with a description and deadline.",
                    e.getMessage());
        }

        // Trying to add as Event
        try {
            taskList.add(TaskList.TaskType.TODO, "todo", "2023-08-26 23:59", "2023-08-27 23:59");
            fail();
        } catch (Exception e) {
            assertEquals("Only Event tasks can be added with a description, start and end date/time.",
                    e.getMessage());
        }
        try {
            taskList.add(TaskList.TaskType.DEADLINE, "todo", "2023-08-26 23:59", "2023-08-27 23:59");
            fail();
        } catch (Exception e) {
            assertEquals("Only Event tasks can be added with a description, start and end date/time.",
                    e.getMessage());
        }
    }

``` 

**Suggestion:** Consider applying [SLAP (and other abstraction mechanisms)](https://nus-cs2103-ay2324s1.github.io/website//se-book-adapted/chapters/codeQuality.html#guideline-maximise-readability) to shorten methods e.g., extract some code blocks into separate methods. You may ignore this suggestion if you think a longer method is justified in a particular case.

### Aspect: Class size

No easy-to-detect issues :+1: 

### Aspect: Header Comments

Example from [`src/main/java/duke/Duke.java` lines `178-184`](https://github.com/jiakai-17/ip/blob/cec39d804c6bf93ae7827ec374a8631a48eefb7f/src/main/java/duke/Duke.java#L178..L184):

```java

    /**
     * Try to mark a task as done.
     *
     * @param argument The task number, as a String.
     * @return Output of the mark command.
     * @throws DukeIllegalArgumentException If the task number is not an integer.
     */

```

Example from [`src/main/java/duke/Duke.java` lines `196-202`](https://github.com/jiakai-17/ip/blob/cec39d804c6bf93ae7827ec374a8631a48eefb7f/src/main/java/duke/Duke.java#L196..L202):

```java

    /**
     * Try to unmark a task as done.
     *
     * @param argument The task number, as a String.
     * @return Output of the unmark command.
     * @throws DukeIllegalArgumentException If the task number is not an integer.
     */

```

Example from [`src/main/java/duke/Duke.java` lines `214-220`](https://github.com/jiakai-17/ip/blob/cec39d804c6bf93ae7827ec374a8631a48eefb7f/src/main/java/duke/Duke.java#L214..L220):

```java

    /**
     * Try to add a Deadline task.
     *
     * @param argument The description and date/time of the Deadline task.
     * @return Output of the add Deadline command.
     * @throws DukeIllegalArgumentException If the argument has missing parameters.
     */

``` 

**Suggestion:** Ensure method/class header comments follow the format specified in the coding standard, in particular, the phrasing of the overview statement.

### Aspect: Recent Git Commit Message

No easy-to-detect issues :+1: 

### Aspect: Binary files in repo

No easy-to-detect issues :+1: 

----

:information_source: The bot account used to post this issue is un-manned. **Do not reply to this post** (as those replies will not be read). Instead, contact `cs2103@comp.nus.edu.sg` if you want to follow up on this post.

**Comment by jiakai-17** [comment]
Resolved in https://github.com/jiakai-17/ip/commit/b9df6550ee262b53cf06a01a849e8fb32fce0c0b
